import 'package:flutter/material.dart';
import 'package:flutter_guide/src/features/catalog/data/samples/sample_names/widget_names.dart';
import 'package:flutter_guide/src/features/home/widgets/component_groups/component_group_model.dart';

/// The predefined component groups shown on the home screen.
final componentGroups = <ComponentGroupModel>[
  ComponentGroupModel(
    icon: Icons.text_fields,
    title: (l10n) => l10n.textGroup,
    components: <String>[
      WidgetNames.editableTextWidget,
      WidgetNames.richTextWidget,
      WidgetNames.selectableTextMaterial,
      WidgetNames.textWidget,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.crop_16_9,
    title: (l10n) => l10n.buttonGroup,
    components: <String>[
      WidgetNames.backButtonMaterial,
      WidgetNames.cupertinoButtonCupertino,
      WidgetNames.cupertinoSegmentedControlCupertino,
      WidgetNames.cupertinoSlidingSegmentedControlCupertino,
      WidgetNames.elevatedButtonMaterial,
      WidgetNames.filledButtonMaterial,
      WidgetNames.floatingActionButtonMaterial,
      WidgetNames.iconButtonMaterial,
      WidgetNames.outlinedButtonMaterial,
      WidgetNames.popupMenuButtonMaterial,
      WidgetNames.segmentedButtonMaterial,
      WidgetNames.textButtonMaterial,
      WidgetNames.toggleButtonsMaterial,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.assignment_outlined,
    title: (l10n) => l10n.formGroup,
    components: <String>[
      WidgetNames.autocompleteMaterial,
      WidgetNames.checkboxMaterial,
      WidgetNames.checkboxListTileMaterial,
      WidgetNames.cupertinoFormSectionCupertino,
      WidgetNames.cupertinoRadioCupertino,
      WidgetNames.cupertinoSearchTextFieldCupertino,
      // WidgetNames.cupertinoSliderCupertino,
      WidgetNames.cupertinoSwitchCupertino,
      WidgetNames.cupertinoTextFieldCupertino,
      WidgetNames.dropdownButtonMaterial,
      WidgetNames.dropdownMenuMaterial,
      WidgetNames.formWidget,
      WidgetNames.radioMaterial,
      WidgetNames.radioListTileMaterial,
      WidgetNames.rangeSliderMaterial,
      WidgetNames.searchBarMaterial,
      WidgetNames.sliderMaterial,
      WidgetNames.switchWidget,
      WidgetNames.switchListTileMaterial,
      WidgetNames.textFieldMaterial,
      WidgetNames.textFormFieldMaterial,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.event,
    title: (l10n) => l10n.pickerGroup,
    components: <String>[
      WidgetNames.cupertinoDatePickerCupertino,
      WidgetNames.cupertinoPickerCupertino,
      WidgetNames.cupertinoTimerPickerCupertino,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.format_list_bulleted,
    title: (l10n) => l10n.listGroup,
    components: <String>[
      WidgetNames.cupertinoListTileCupertino,
      WidgetNames.expansionPanelListMaterial,
      WidgetNames.expansionTileMaterial,
      WidgetNames.gridViewWidget,
      WidgetNames.listTileMaterial,
      WidgetNames.listViewWidget,
      WidgetNames.pageViewWidget,
      WidgetNames.reorderableListViewMaterial,
      WidgetNames.singleChildScrollViewWidget,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.dashboard_outlined,
    title: (l10n) => l10n.layoutGroup,
    components: <String>[
      WidgetNames.alignWidget,
      WidgetNames.centerWidget,
      WidgetNames.columnWidget,
      WidgetNames.constrainedBoxWidget,
      WidgetNames.containerWidget,
      WidgetNames.expandedWidget,
      WidgetNames.flexibleWidget,
      WidgetNames.flowWidget,
      WidgetNames.indexedStackWidget,
      WidgetNames.positionedWidget,
      WidgetNames.rowWidget,
      WidgetNames.safeAreaWidget,
      WidgetNames.sizedBoxWidget,
      WidgetNames.spacerWidget,
      WidgetNames.stackWidget,
      WidgetNames.tableWidget,
      WidgetNames.wrapWidget,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.navigation_outlined,
    title: (l10n) => l10n.navigationGroup,
    components: <String>[
      WidgetNames.appBarMaterial,
      WidgetNames.bottomAppBarMaterial,
      WidgetNames.bottomNavigationBarMaterial,
      WidgetNames.cupertinoNavigationBarCupertino,
      WidgetNames.cupertinoNavigationBarBackButtonCupertino,
      WidgetNames.cupertinoPageScaffoldCupertino,
      WidgetNames.cupertinoTabBarCupertino,
      WidgetNames.cupertinoTabScaffoldCupertino,
      WidgetNames.drawerMaterial,
      WidgetNames.navigationBarMaterial,
      WidgetNames.navigationRailMaterial,
      WidgetNames.scaffoldMaterial,
      WidgetNames.tabBarSampleMaterial,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.chat_bubble_outline,
    title: (l10n) => l10n.dialogAndOverlayGroup,
    components: <String>[
      WidgetNames.alertDialogMaterial,
      WidgetNames.cupertinoActionSheetCupertino,
      WidgetNames.cupertinoAlertDialogCupertino,
      WidgetNames.cupertinoContextMenuCupertino,
      WidgetNames.cupertinoDialogActionCupertino,
      WidgetNames.dialogMaterial,
      WidgetNames.materialBannerMaterial,
      WidgetNames.menuAnchorMaterial,
      WidgetNames.simpleDialogMaterial,
      WidgetNames.snackBarMaterial,
      WidgetNames.tooltipMaterial,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.info_outline,
    title: (l10n) => l10n.displayGroup,
    components: <String>[
      WidgetNames.actionChipMaterial,
      WidgetNames.badgeMaterial,
      WidgetNames.bannerWidget,
      WidgetNames.cardMaterial,
      WidgetNames.chipMaterial,
      WidgetNames.choiceChipMaterial,
      WidgetNames.circleAvatarMaterial,
      WidgetNames.circularProgressIndicatorMaterial,
      WidgetNames.cupertinoActivityIndicatorCupertino,
      WidgetNames.dataTableMaterial,
      WidgetNames.dividerMaterial,
      WidgetNames.filterChipMaterial,
      WidgetNames.flutterLogoMaterial,
      WidgetNames.imageWidget,
      WidgetNames.inputChipMaterial,
      WidgetNames.linearProgressIndicatorMaterial,
      WidgetNames.paginatedDataTableMaterial,
      WidgetNames.placeholderWidget,
      WidgetNames.stepperMaterial,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.auto_awesome,
    title: (l10n) => l10n.effectsGroup,
    components: <String>[
      WidgetNames.animatedAlignWidget,
      WidgetNames.animatedContainerWidget,
      WidgetNames.animatedOpacityWidget,
      WidgetNames.backdropFilterWidget,
      WidgetNames.clipOvalWidget,
      WidgetNames.clipPathWidget,
      WidgetNames.clipRRectWidget,
      WidgetNames.colorFilteredWidget,
      WidgetNames.decoratedBoxWidget,
      WidgetNames.opacityWidget,
      WidgetNames.themeMaterial,
      WidgetNames.visibilityWidget,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.touch_app_outlined,
    title: (l10n) => l10n.interactionGroup,
    components: <String>[
      WidgetNames.dismissibleMaterial,
      WidgetNames.draggableWidget,
      WidgetNames.gestureDetectorWidget,
      WidgetNames.ignorePointerWidget,
      WidgetNames.inkWellMaterial,
      WidgetNames.interactiveViewerWidget,
    ],
  ),
  ComponentGroupModel(
    icon: Icons.autorenew,
    title: (l10n) => l10n.builderGroup,
    components: <String>[
      WidgetNames.futureBuilderWidget,
      WidgetNames.listenableBuilderWidget,
      WidgetNames.valueListenableBuilderWidget,
    ],
  ),
];
